# ML Practical 3
# Name:- Devashish Tadaskar
# Roll no:- C-C2-25

# To implement Find s and candidate elimination algorithm on the enjoy sports dataset and compare the generated hypotheses

In [ ]:
import pandas as pd
df=pd.read_csv("enjoy.csv")

In [ ]:
df.head()

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes
4  Sunny    Cold   Normal    Weak  Warm     Same         No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sky         10 non-null     object
 1   AirTemp     10 non-null     object
 2   Humidity    10 non-null     object
 3   Wind        10 non-null     object
 4   Water       10 non-null     object
 5   Forecast    10 non-null     object
 6   EnjoySport  10 non-null     object
dtypes: object(7)
memory usage: 692.0+ bytes

In [ ]:
df.tail()

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [ ]:
df.isnull().sum()

Sky           0
AirTemp       0
Humidity      0
Wind          0
Water         0
Forecast      0
EnjoySport    0
dtype: int64

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:,-1].values

In [ ]:
import numpy as np
def find_s(X, y):
    hypothesis = None
    print ("initial Hypothesis :",hypothesis)
    for i in range(len(X)):
        if y[i] == "Yes":
            if hypothesis is None:
                hypothesis = X[i]
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != X[i][j]:
                        hypothesis[j] = "?"
        print(f"\nAfter Training Example {i+1}")
        print(hypothesis)
    return hypothesis
final_hypothesis = find_s(X,y)
print("\nFinal Hypothesis :",final_hypothesis)

initial Hypothesis : None

After Training Example 1
['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']

After Training Example 2
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 3
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 4
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 5
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 6
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 7
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 8
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 9
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 10
['Sunny' 'Warm' '?' '?' '?' '?']

Final Hypothesis : ['Sunny' 'Warm' '?' '?' '?' '?']

# Candidate Elimination Algorithm

In [ ]:
import copy
def candidate_elimination(concepts, target):
    specific = concepts[0].copy()
    general = ["?" for i in range(len(specific))]
    print ("\n Initial S:", specific)
    print ("\n Initial G:", general)
    for i,h in enumerate(concepts):
      if target[i]  == "Yes":
        for x in range(len(specific)):
            if h[x] != specific[x]:
                specific[x] = "?"
        else:
            for x in range(len(specific)):
                if h[x] != specific[x]:
                   general.append(["?" if j!= "?" else specific[x] for j in range(len(specific))])
      print("\nExample", i+1)
      print("S=" , specific)
      print("G=", general)
    return specific,general
S, G = candidate_elimination(X, y)
print("\nFinal Specific Boundary:", S)
print("\nFinal General Boundary:", G)
for g in G:
    print(g)
    for s in S:
        print(s)

 Initial S: ['Sunny' 'Warm' '?' '?' '?' '?']

 Initial G: ['?', '?', '?', '?', '?', '?']

Example 1
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?']

Example 2
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 3
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 4
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 5
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 6
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 7
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 8
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 9
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 10
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Final Specific Boundary: ['Sunny' 'Warm' '?' '?' '?' '?']

Final General Boundary: ['?', '?', '?', '?', '?', '?', ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]
?
Sunny
Warm
?
?
?
?
?
Sunny
Warm
?
?
?
?
?
Sunny
Warm
?
?
?
?
?
Sunny
Warm
?
?
?
?
?
Sunny
Warm
?
?
?
?
?
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?
['?', '?', '?', '?', '?', '?']
Sunny
Warm
?
?
?
?